server:
  port: 3000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

exchange:
  token: decc2f1378fdd448f7596b870cf25d32


